spring:
  profiles.active: ${APP_PROFILE:test}
  security.oauth2.client:
    registration:
     github:
       clientId: ${GITHUB_CLIENT_ID:none}
       clientSecret: ${GITHUB_CLIENT_SECRET:none}
#      google:
#        clientId: ${GOOGLE_CLIENT_ID:none}
#        clientSecret: ${GOOGLE_CLIENT_SECRET:none}

app:
  cors:
    allowedOrigins: ${ALLOWED_ORIGINS:http://localhost:3000}
  oauth2.authorizedRedirectUris:
    - http://localhost:3000/oauth2/redirect
    - myandroidapp://oauth2/redirect
    - myiosapp://oauth2/redirect