spring:
  profiles.active: ${APP_PROFILE:test}
  security.oauth2.client:
    registration:
     github:
       clientId: ${GITHUB_CLIENT_ID:c3171501c08ea21a50cf}
       clientSecret: ${GITHUB_CLIENT_SECRET:36ec3f2679abede8324e37fd37c0e65d66af1c50}
#      google:
#        clientId: ${GOOGLE_CLIENT_ID:275666884294-9o9n8m6u5n58m66ocq4he8oc12tgs42r.apps.googleusercontent.com}
#        clientSecret: ${GOOGLE_CLIENT_SECRET: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}

app:
  cors:
    allowedOrigins: http://localhost:3000
  oauth2.authorizedRedirectUris:
    - http://localhost:3000/oauth2/redirect
    - myandroidapp://oauth2/redirect
    - myiosapp://oauth2/redirect